
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author laboratorio
 */
public class JFrame_Principal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrame_Principal.class.getName());

    /**
     * Creates new form JFrame_Principal
     */
    public JFrame_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JButton_ghost1 = new javax.swing.JButton();
        JButton_frutinha = new javax.swing.JButton();
        JButton_ghost2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JButton_ghost1.setText("1");
        JButton_ghost1.setFocusable(false);
        JButton_ghost1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_ghost1ActionPerformed(evt);
            }
        });

        JButton_frutinha.setText("@");
        JButton_frutinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_frutinhaActionPerformed(evt);
            }
        });
        JButton_frutinha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JButton_frutinhaKeyPressed(evt);
            }
        });

        JButton_ghost2.setText("2");
        JButton_ghost2.setFocusable(false);
        JButton_ghost2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_ghost2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(JButton_ghost1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(JButton_frutinha, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(289, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(190, Short.MAX_VALUE)
                    .addComponent(JButton_ghost2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(168, 168, 168)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(JButton_ghost1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(JButton_frutinha, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(120, 120, 120)
                    .addComponent(JButton_ghost2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(142, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButton_ghost1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_ghost1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JButton_ghost1ActionPerformed

    private void JButton_frutinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_frutinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JButton_frutinhaActionPerformed

    private void JButton_ghost2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_ghost2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JButton_ghost2ActionPerformed

    private void JButton_frutinhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JButton_frutinhaKeyPressed
        // TODO add your handling code here:

        switch (evt.getKeyCode()) {
            case 38: // ghost1 cima
                new Thread() {
                    @Override
                    public void run() {
                        System.out.println("indo para cima");
                        Movimenta.cima(JButton_ghost1);
                    }
                }.start();
                break;
            case 40: // ghost1 baixo
                new Thread() {
                    @Override
                    public void run() {
                        System.out.println("indo para baixo");
                        Movimenta.baixo(JButton_ghost1, this);
                    }
                }.start();
                break;
            case 37: // ghost1 esquerda
                new Thread() {
                    @Override
                    public void run() {
                        System.out.println("indo para esquerda");
                        Movimenta.esquerda(JButton_ghost1);
                    }
                }.start();
                break;
            case 39: // ghost1 direita
                new Thread() {
                    @Override
                    public void run() {
                        System.out.println("indo para direita");
                        Movimenta.direita(JButton_ghost1, this);
                    }
                }.start();
                break;
            case 87: // ghost2 cima
                new Thread() {
                    @Override
                    public void run() {
                        System.out.println("indo para cima");
                        Movimenta.cima(JButton_ghost2);
                    }
                }.start();
                break;
            case 83: // ghost2 baixo
                new Thread() {
                    @Override
                    public void run() {
                        System.out.println("indo para baixo");
                        Movimenta.baixo(JButton_ghost2, this);
                    }
                }.start();
                break;
            case 65: // ghost2 esquerda
                new Thread() {
                    @Override
                    public void run() {
                        System.out.println("indo para esquerda");
                        Movimenta.esquerda(JButton_ghost2);
                    }
                }.start();
                break;
            case 68: // ghost2 direita
                new Thread() {
                    @Override
                    public void run() {
                        System.out.println("indo para direita");
                        Movimenta.direita(JButton_ghost2, this);
                    }
                }.start();
                break;
            default:
                throw new AssertionError();
        }

        if (JButton_ghost1.getBounds().intersects(JButton_frutinha.getBounds())) {
            Movimenta.sorteiaPosicao(JButton_frutinha, this);
        }

        System.out.println("pressionei..." + evt.getKeyChar());
        System.out.println("pressionei..." + evt.getKeyCode());
        System.out.println("pressionei..." + evt.getExtendedKeyCode());
    }//GEN-LAST:event_JButton_frutinhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrame_Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_frutinha;
    private javax.swing.JButton JButton_ghost1;
    private javax.swing.JButton JButton_ghost2;
    // End of variables declaration//GEN-END:variables
}
